### PR TITLE
Improved Docs and raise minimal rustc version to 1.13.0

### PR DESCRIPTION
**Pull request by dns2utf8**
Hi All

I added some documentation:
* Explicit magic constant
* Remove the last warning while running the tests
* Document the development with rustup

Best,
Stefan

### CODE REVIEW

**Comment by dns2utf8** [comment]
So it turns out that `libc` < 0.2.40 require rust 1.13.0 or later.
@frewsxcv Should we up our requirements too?

**Comment by frewsxcv** [comment]
Yeah, I think it's fine to bump to 1.13.0

**Comment by frewsxcv** [comment]
Also FYI, I just gave you 'owner' privileges for this GH Org

**Comment by dns2utf8** [comment]
Perfect.
Thank you for the access :)

bors r+

**Pull request merged**
